# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparcamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('direccion', models.CharField(max_length=256)),
                ('enlace', models.CharField(max_length=256)),
                ('latitud', models.CharField(max_length=256)),
                ('longitud', models.CharField(max_length=256)),
                ('barrio', models.CharField(max_length=256)),
                ('distrito', models.CharField(max_length=256)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
