# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparcamiento',
            old_name='enlace',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='aparcamiento',
            old_name='latitud',
            new_name='coordenadas',
        ),
        migrations.RenameField(
            model_name='aparcamiento',
            old_name='longitud',
            new_name='url',
        ),
        migrations.AddField(
            model_name='aparcamiento',
            name='accesibilidad',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
