# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfinalapp', '0002_auto_20170522_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('aparcamiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfinalapp.Aparcamiento')),
            ],
        ),
    ]
