# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinalapp', '0004_auto_20170522_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=256)),
                ('contenido', models.CharField(max_length=256)),
            ],
        ),
    ]
