# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myfinalapp', '0005_css'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparcamiento_Seleccionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('aparcamiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfinalapp.Aparcamiento')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
